### ISSUE TITLE
Question: What made you make this over using one of the others? 

### ISSUE THREAD

**Issue by mbbroberg** [Cornellio/puppet-riak1#1]
Hey - I'm doing some spring cleaning on Basho repos and see we have https://github.com/basho/puppet-riak

I'm not intimately familiar with Puppet, so I'm curious to know what made you want to build your own as oppose to using the code above. 

I'll be curating more Puppet code for Riak on here. I'd love your feedback on the process: https://github.com/basho-labs/the-riak-community/blob/master/config-mgmt-strategy.md

Thanks! Feel free to ping me at mbrender @ basho as well.

**Comment by Cornellio** [comment]
Hello,

I'm sorry, I totally missed this message and just now read it.

Not sure if it helps at this point, but I basically wanted to write my own Riak module as a way to get more experience with Puppet and wanted it to create a cluster and do tuning.

I was hoping to help with the new Riak 2 module but it seems to be in a holding pattern.

Cheers,
Pete
